version: 2
jobs:
  test:
    working_directory: /go/src/github.com/graphite-ng/carbon-relay-ng
    docker:
      - image: circleci/golang:1.10.3
    steps:
      - checkout
      - run: go test -v -race ./...

  build:
    working_directory: /go/src/github.com/graphite-ng/carbon-relay-ng
    docker:
      - image: circleci/golang:1.10.3
    steps:
      - checkout
      - run: go get github.com/shuLhan/go-bindata/cmd/go-bindata
      - run: make build-linux # note, this runs go-bindata again
      # ideally we'd make sure that if go-bindata generated new content, we fail.
      # because devs should have run go-bindata and checked in changes already.
      # but because git checkout will change the timestamps and mode, it'll generate slight differences, and it's hard to filter those out
      # so for now, we just let it slip and assume devs will do a good enough job maintaining the generated data
      # - git diff --exit-code
      - run: make build-win
      - persist_to_workspace:
          root: .
          paths:
            - carbon-relay-ng
            - carbon-relay-ng.exe

  deploy:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: gem install package_cloud
      - store_artifacts:
          path: build
      - store_artifacts:
          path: carbon-relay-ng.exe
      - store_artifacts:
          path: carbon-relay-ng
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
